title: Lovers, Beekeepers, Epilepsy, Fainting, and the Plague
description: Daily writing and experiments from Saint Rhian.
url: "https://saintrhian.github.io"
theme: null
markdown: kramdown
permalink: /:year/:month/:day/:title/
timezone: America/Chicago

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post
  - scope:
      path: ""
    values:
      layout: default
